name: Build and Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - release/*
    - greenkeeper/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js lts/Hydrogen
      uses: actions/setup-node@v3
      with:
        node-version: lts/Hydrogen
    - run: npm ci
    - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run test
